/* Admin select options, mirrored from the frontend registries.
 *
 * Generated from the design's own data by tools/visual-parity/gen-registries.mjs.
 * Source: the same design data that generates web/lib/registries/*
 *
 * The CMS stores the KEY; this file owns the artwork. Editors never paste SVG.
 * Each registry exports its lookup and an `options` array — cms/src/lib imports the same
 * options so an admin dropdown cannot drift from the code that renders it. */

type Option = { label: string; value: string }

/** Keys in web/lib/registries/icons.ts */
export const iconOptions: Option[] = [
  { label: 'ai-transformation', value: 'ai-transformation' },
  { label: 'digital-engineering', value: 'digital-engineering' },
  { label: 'business-transformation', value: 'business-transformation' },
  { label: 'digital-experience', value: 'digital-experience' },
  { label: 'growth-transformation', value: 'growth-transformation' },
  { label: 'products-and-platforms', value: 'products-and-platforms' },
  { label: 'evoq', value: 'evoq' },
  { label: 'blogs', value: 'blogs' },
  { label: 'case-studies', value: 'case-studies' },
  { label: 'whitepapers', value: 'whitepapers' },
  { label: 'featured-projects', value: 'featured-projects' },
  { label: 'about', value: 'about' },
  { label: 'our-approach', value: 'our-approach' },
  { label: 'clients', value: 'clients' },
  { label: 'careers', value: 'careers' },
  { label: 'customer-experience', value: 'customer-experience' },
  { label: 'employee-productivity', value: 'employee-productivity' },
  { label: 'business-operations', value: 'business-operations' },
  { label: 'decision-making', value: 'decision-making' },
  { label: 'digital-products', value: 'digital-products' },
  { label: 'software-engineering', value: 'software-engineering' },
  { label: 'simpler-operations', value: 'simpler-operations' },
  { label: 'better-customer-relationships', value: 'better-customer-relationships' },
  { label: 'faster-execution', value: 'faster-execution' },
  { label: 'connected-business-capabilities', value: 'connected-business-capabilities' },
  { label: 'scalable-operations', value: 'scalable-operations' },
  { label: 'new-business-capabilities', value: 'new-business-capabilities' },
  { label: 'launch-faster', value: 'launch-faster' },
  { label: 'modernize-with-confidence', value: 'modernize-with-confidence' },
  { label: 'scale-as-demand-grows', value: 'scale-as-demand-grows' },
  { label: 'connect-what-already-exists', value: 'connect-what-already-exists' },
  { label: 'improve-reliability', value: 'improve-reliability' },
  { label: 'prepare-for-what-s-next', value: 'prepare-for-what-s-next' },
  { label: 'frontend', value: 'frontend' },
  { label: 'backend', value: 'backend' },
  { label: 'frameworks', value: 'frameworks' },
  { label: 'full-stack', value: 'full-stack' },
  { label: 'content-platforms', value: 'content-platforms' },
  { label: 'architecture-and-engineering', value: 'architecture-and-engineering' },
  { label: 'increase-qualified-demand', value: 'increase-qualified-demand' },
  { label: 'improve-visibility', value: 'improve-visibility' },
  { label: 'turn-interest-into-action', value: 'turn-interest-into-action' },
  { label: 'improve-marketing-efficiency', value: 'improve-marketing-efficiency' },
  { label: 'build-lasting-visibility', value: 'build-lasting-visibility' },
  { label: 'measure-what-matters', value: 'measure-what-matters' },
  { label: 'web-application-engineering', value: 'web-application-engineering' },
  { label: 'frontend-engineering', value: 'frontend-engineering' },
  { label: 'backend-engineering', value: 'backend-engineering' },
  { label: 'cms-and-content-platforms', value: 'cms-and-content-platforms' },
  { label: 'application-modernization', value: 'application-modernization' },
  { label: 'integration-and-apis', value: 'integration-and-apis' },
  { label: 'full-stack-engineering', value: 'full-stack-engineering' },
  { label: 'fast-experiences', value: 'fast-experiences' },
  { label: 'scalable-architecture', value: 'scalable-architecture' },
  { label: 'easier-evolution', value: 'easier-evolution' },
  { label: 'connected-applications', value: 'connected-applications' },
  { label: 'reliable-releases', value: 'reliable-releases' },
  { label: 'cloud-application-engineering', value: 'cloud-application-engineering' },
  { label: 'cloud-modernization', value: 'cloud-modernization' },
  { label: 'cloud-migration', value: 'cloud-migration' },
  { label: 'cloud-architecture', value: 'cloud-architecture' },
  { label: 'devops-and-automation', value: 'devops-and-automation' },
  { label: 'cloud-integration', value: 'cloud-integration' },
  { label: 'cloud-security-and-resilience', value: 'cloud-security-and-resilience' },
  { label: 'scale-when-needed', value: 'scale-when-needed' },
  { label: 'resilient-operations', value: 'resilient-operations' },
  { label: 'faster-delivery', value: 'faster-delivery' },
  { label: 'better-efficiency', value: 'better-efficiency' },
  { label: 'secure-foundations', value: 'secure-foundations' },
  { label: 'native-mobile-development', value: 'native-mobile-development' },
  { label: 'cross-platform-development', value: 'cross-platform-development' },
  { label: 'mobile-application-modernization', value: 'mobile-application-modernization' },
  { label: 'mobile-ui-engineering', value: 'mobile-ui-engineering' },
  { label: 'mobile-backend-and-apis', value: 'mobile-backend-and-apis' },
  { label: 'mobile-integration', value: 'mobile-integration' },
  { label: 'reliable-performance', value: 'reliable-performance' },
  { label: 'seamless-experiences', value: 'seamless-experiences' },
  { label: 'secure-applications', value: 'secure-applications' },
  { label: 'faster-evolution', value: 'faster-evolution' },
  { label: 'connected-workflows', value: 'connected-workflows' },
  { label: 'test-automation', value: 'test-automation' },
  { label: 'api-and-integration-testing', value: 'api-and-integration-testing' },
  { label: 'performance-engineering', value: 'performance-engineering' },
  { label: 'continuous-testing', value: 'continuous-testing' },
  { label: 'application-quality-assessment', value: 'application-quality-assessment' },
  { label: 'security-testing', value: 'security-testing' },
  { label: 'ai-assisted-quality-engineering', value: 'ai-assisted-quality-engineering' },
  { label: 'earlier-defect-detection', value: 'earlier-defect-detection' },
  { label: 'higher-test-coverage', value: 'higher-test-coverage' },
  { label: 'qe-reliable-releases', value: 'qe-reliable-releases' },
  { label: 'better-performance', value: 'better-performance' },
  { label: 'continuous-quality', value: 'continuous-quality' },
  { label: 'crm', value: 'crm' },
  { label: 'campaigns', value: 'campaigns' },
  { label: 'practice-management', value: 'practice-management' },
  { label: 'serviceops', value: 'serviceops' },
  { label: 'desk', value: 'desk' },
  { label: 'projects', value: 'projects' },
  { label: 'sync', value: 'sync' },
  { label: 'inventory', value: 'inventory' },
  { label: 'cpq', value: 'cpq' },
  { label: 'billing', value: 'billing' },
  { label: 'hrms', value: 'hrms' },
  { label: 'skillberry', value: 'skillberry' },
  { label: 'reduce-disconnected-work', value: 'reduce-disconnected-work' },
  { label: 'adapt-the-platform', value: 'adapt-the-platform' },
  { label: 'grow-without-unnecessary-complexity', value: 'grow-without-unnecessary-complexity' },
  { label: 'one-view-of-the-customer', value: 'one-view-of-the-customer' },
  { label: 'cleaner-sales-processes', value: 'cleaner-sales-processes' },
  { label: 'less-manual-work', value: 'less-manual-work' },
  { label: 'better-visibility', value: 'better-visibility' },
  { label: 'a-platform-that-can-evolve', value: 'a-platform-that-can-evolve' },
  { label: 'shift-fast', value: 'shift-fast' },
  { label: 'shift-secure', value: 'shift-secure' },
  { label: 'shift-scalable', value: 'shift-scalable' },
  { label: 'shift-easy-to-evolve', value: 'shift-easy-to-evolve' },
  { label: 'shift-connected', value: 'shift-connected' },
  { label: 'shift-integrated', value: 'shift-integrated' },
  { label: 'shift-resilient', value: 'shift-resilient' },
  { label: 'shift-efficient', value: 'shift-efficient' },
  { label: 'shift-reliable', value: 'shift-reliable' },
  { label: 'shift-cross-device', value: 'shift-cross-device' },
  { label: 'shift-high-performing', value: 'shift-high-performing' },
  { label: 'shift-earlier-detection', value: 'shift-earlier-detection' },
  { label: 'shift-automated', value: 'shift-automated' },
  { label: 'shift-measured', value: 'shift-measured' },
  { label: 'qe-shift-reliable', value: 'qe-shift-reliable' },
]

/** Keys in web/lib/registries/motifs.ts, plus the animated orb. */
export const motifOptions: Option[] = [
  { label: 'ai-transformation', value: 'ai-transformation' },
  { label: 'digital-engineering', value: 'digital-engineering' },
  { label: 'business-transformation', value: 'business-transformation' },
  { label: 'digital-experience', value: 'digital-experience' },
  { label: 'growth-transformation', value: 'growth-transformation' },
  { label: 'products-and-platforms', value: 'products-and-platforms' },
]

/** Keys in web/lib/registries/mocks.ts */
export const productMockOptions: Option[] = [
  { label: 'crm', value: 'crm' },
  { label: 'campaigns', value: 'campaigns' },
  { label: 'practice-management', value: 'practice-management' },
  { label: 'serviceops', value: 'serviceops' },
  { label: 'desk', value: 'desk' },
  { label: 'projects', value: 'projects' },
  { label: 'sync', value: 'sync' },
  { label: 'inventory', value: 'inventory' },
  { label: 'cpq', value: 'cpq' },
  { label: 'billing', value: 'billing' },
  { label: 'hrms', value: 'hrms' },
  { label: 'skillberry', value: 'skillberry' },
]

/** Values in web/lib/registries/visuals.ts */
export const heroVisualOptions: Option[] = [
  { label: 'Home — particle canvas', value: 'home-canvas' },
  { label: 'Services — DNA helix', value: 'services-dna' },
  { label: 'AI — grain orb + particles', value: 'ai-orb' },
  { label: 'Business — rotating arc', value: 'bt-arc' },
  { label: 'Engineering — hex lattice', value: 'de-hex' },
  { label: 'Experience — cursor motif', value: 'dx-cursor' },
  { label: 'Growth — rising chart', value: 'gt-chart' },
  { label: 'Sub-service — stacked windows', value: 'wae-windows' },
  { label: 'Cloud engineering — cloud + nodes', value: 'ce-cloud' },
  { label: 'Mobile engineering — phone mockup', value: 'me-phone' },
  { label: 'Quality engineering — release pipeline', value: 'qe-pipeline' },
  { label: 'EVOQ — team photo (upload it as the hero image)', value: 'evoq-suite' },
  { label: 'Zoho — partner logo card (upload the logo as the hero image)', value: 'zh-logo-card' },
  { label: 'Salesforce — logo card (upload the logo as the hero image)', value: 'sf-logo-card' },
  { label: 'No visual (copy only)', value: 'none' },
]

/** Keys in web/lib/registries/ai-engineering-mocks.ts */
export const aiEngineeringMockOptions: Option[] = [
  { label: 'Digital engineering', value: 'digital-engineering' },
  { label: 'Web & application engineering', value: 'web-application-engineering' },
  { label: 'Cloud engineering', value: 'cloud-engineering' },
  { label: 'Mobile engineering', value: 'mobile-engineering' },
  { label: 'Quality engineering', value: 'quality-engineering' },
]
