// ESLint flat config.
//
// `next lint` was removed in Next 16 and `next build` no longer lints, so this is invoked
// directly via `pnpm lint` and as its own CI step. @next/eslint-plugin-next defaults to flat
// config from Next 16 onward.

import js from '@eslint/js'
import nextPlugin from '@next/eslint-plugin-next'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'media/**',
      'src/payload-types.ts', // generated by `payload generate:types`
      '**/importMap.js', // generated by `payload generate:importmap`
      'src/migrations/*.ts', // generated by `payload migrate:create`
      'src/migrations/*.json',
      'next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
    },
  },

  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // Payload config and hook signatures use `any` in places where the upstream types are
      // deliberately loose. Warn rather than error so it stays visible without blocking.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
)
